-- -- 코드를 입력하세요

SELECT CAR.car_id, CAR.car_type, CAR.DAILY_FEE * 30 * (1-(DISCOUNT.discount_rate/100)) FEE
FROM CAR_RENTAL_COMPANY_CAR CAR, CAR_RENTAL_COMPANY_DISCOUNT_PLAN DISCOUNT
WHERE CAR.CAR_TYPE = DISCOUNT.CAR_TYPE
AND DISCOUNT.DURATION_TYPE = '30일 이상'
AND CAR.CAR_TYPE in ('세단','SUV')
AND CAR.DAILY_FEE * 30 * (1-(DISCOUNT.discount_rate/100))  >= 500000 AND  CAR.DAILY_FEE * 30 * (1-(DISCOUNT.discount_rate/100))  < 2000000
AND CAR.car_id NOT IN (
    SELECT car_id
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE start_date <= TO_DATE('2022-11-30', 'RRRR-MM-DD')
    AND end_date >= TO_DATE('2022-11-01', 'RRRR-MM-DD')
    -- ORDER BY car_id
)
ORDER BY FEE DESC, CAR.car_type ASC, CAR.car_id DESC

