
-- SELECT *
-- FROM REST_INFO
-- WHERE ADDRESS LIKE '%서울%'

-- SELECT *
-- FROM REST_REVIEW, REST_INFO
-- WHERE REST_REVIEW.rest_id = REST_INFO.rest_id
-- AND ADDRESS LIKE '%서울%'

-- 코드를 입력하세요
-- SELECT REST.REST_ID, REST.REST_NAME, REST.FOOD_TYPE, REST.FAVORITES, REST.ADDRESS, CASE WHEN REVIEW.SCORE IS NULL THEN 0.00
--                                                                                         ELSE REVIEW.SCORE END AS SCORE
-- FROM REST_INFO REST FULL OUTER JOIN (
--     SELECT REST_ID, ROUND(AVG(REVIEW_SCORE),2) SCORE
--     FROM REST_REVIEW 
--     GROUP BY REST_ID
-- ) REVIEW ON  REST.REST_ID = REVIEW.REST_ID
-- WHERE REST.ADDRESS LIKE '서울%'
-- ORDER BY SCORE DESC, FAVORITES DESC

SELECT REST.REST_ID, REST.REST_NAME, REST.FOOD_TYPE, REST.FAVORITES, REST.ADDRESS, CASE WHEN REVIEW.SCORE IS NULL THEN 0.00
                                                                                        ELSE REVIEW.SCORE END AS SCORE
FROM REST_INFO REST, (
    SELECT REST_ID, ROUND(AVG(REVIEW_SCORE),2) SCORE
    FROM REST_REVIEW 
    GROUP BY REST_ID
) REVIEW 
WHERE REST.REST_ID = REVIEW.REST_ID
AND REST.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC