SELECT *
FROM (SELECT DISTINCT INS.name, INS.datetime
FROM ANIMAL_INS INS
WHERE INS.animal_id not in (
    SELECT animal_id
    FROM ANIMAL_OUTS)
ORDER BY INS.datetime)
WHERE ROWNUM < 4

-- SELECT *
-- FROM ANIMAL_OUTS
-- ORDER BY DATETIME