-- 코드를 입력하세요
SELECT APNT_NO, PT_NAME, PATIENT.PT_NO, DOCTOR.MCDP_CD, DR_NAME, APNT_YMD
FROM PATIENT, DOCTOR, APPOINTMENT
WHERE APPOINTMENT.PT_NO = PATIENT.PT_NO
AND APPOINTMENT.MDDR_ID = DOCTOR.DR_ID
AND DOCTOR.MCDP_CD = 'CS'
AND APNT_CNCL_YN = 'N'
AND TO_CHAR(APNT_YMD,'YYYY-MM-DD') = '2022-04-13'
ORDER BY APNT_YMD ASC