-- 코드를 입력하세요
SELECT ALLHOUR.hour, CASE WHEN REALHOUR.count IS NULL THEN 0
                          ELSE REALHOUR.count END AS COUNT
FROM (SELECT LEVEL -1 hour
FROM DUAL
CONNECT BY LEVEL < 25) ALLHOUR,
(SELECT TO_CHAR(OUTS.datetime,'hh24') HOUR, count(1) count
FROM ANIMAL_OUTS OUTS
GROUP BY TO_CHAR(OUTS.datetime,'hh24')
) REALHOUR
WHERE ALLHOUR.hour = REALHOUR.HOUR(+)
ORDER BY ALLHOUR.HOUR
