-- SELECT CAR_ID, END_DATE, TO_DATE('2022-10-16','RRRR-MM-DD')
-- FROM (SELECT CAR_ID, min(START_DATE) AS START_DATE, max(END_DATE) AS END_DATE
-- FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- GROUP BY CAR_ID)
-- ORDER BY CAR_ID DESC
-- SELECT TO_CHAR(START_DATE,'MM') MONTH, CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID, CAR.records
-- FROM ( CAR, CAR_RENTAL_COMPANY_RENTAL_HISTORY 
-- WHERE CAR.CAR_ID = CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID
-- GROUP BY TO_CHAR(CAR_RENTAL_COMPANY_RENTAL_HISTORY.START_DATE,'MM')
-- ORDER BY CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID DESC
SELECT TO_NUMBER(TO_CHAR(CAR_RENTAL_COMPANY_RENTAL_HISTORY.START_DATE,'MM')) MONTH, CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID, count(1) RECORDS
FROM 
(SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE between TO_DATE('2022-08-01','RRRR-MM-DD') AND TO_DATE('2022-10-31','RRRR-MM-DD')  
GROUP BY CAR_ID
HAVING count(1) >= 5
ORDER BY 1 DESC) HISTORY, CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE HISTORY.CAR_ID = CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID
AND START_DATE between TO_DATE('2022-08-01','RRRR-MM-DD') AND TO_DATE('2022-10-31','RRRR-MM-DD')  
GROUP BY TO_NUMBER(TO_CHAR(CAR_RENTAL_COMPANY_RENTAL_HISTORY.START_DATE,'MM')), CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID
HAVING count(1) >0
ORDER BY MONTH ASC, CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID DESC